export const car = [
  {
    src: "/img/categories/car/1.jpg",
    name: "NEED FOR SPEED 5",
    category: ["Sport", "Multiplayer", "Online"],
    star: "5",
    path: "/img/details/car/1.jpg",
    desc: "Hustle by day and risk it all at night in Need for Speed™ Heat Deluxe Edition, a white-knuckle street racer, where the lines of the law fade as the sun starts to set.",
    link: "https://steamdb.info/app/1222680/",
  },
  {
    src: "/img/categories/car/2.jpg",
    name: "NEED FOR SPEED PAY",
    category: ["Sport", "Multiplayer", "Online"],
    star: "4.5",
    path: "/img/details/car/2.jpg",
    desc: "Set in the underworld of Fortune Valley, you and your crew were divided by betrayal and reunited by revenge to take down The House, a nefarious cartel that rules the city’s casinos, criminals and cops. In this corrupt gambler’s paradise, the stakes are high and The House always wins.",
    link: "https://steamdb.info/app/1262580/",
  },
  {
    src: "/img/categories/car/3.jpg",
    name: "ANARCHY RACER",
    category: ["Sport", "Multiplayer", "Online"],
    star: "5",
    path: "/img/details/car/3.jpg",
    desc: "Battle for survival in a savage post-apocalyptic desert in Anarchy Racers: Fury Roads. Upgrade cars, destroy enemies in dynamic modes, and conquer the ultimate survival challenge!",
    link: "https://steamdb.info/app/3215380/",
  },
  {
    src: "/img/categories/car/4.jpg",
    name: "TRAFIC REACE",
    category: ["Sport", "Multiplayer", "Online"],
    star: "3",
    path: "/img/details/car/4.jpg",
    desc: "Fastest Cars Traffic Racer invites you to endless highways for speed and adventure! Prepare for a real racing experience with four different racing modes and eye-catching graphics.",
    link: "https://steamdb.info/app/2598970/",
  },
  {
    src: "/img/categories/car/5.jpg",
    name: "WAR AGAINST POLICE",
    category: ["Sport", "Multiplayer", "Online"],
    star: "5",
    path: "/img/details/car/5.jpg",
    desc: "You will become part of an elite police squad. Your mission is to engage in battles with unpredictable street racers who pose a danger to ordinary citizens on the roads. You will have to control various police vehicles and use your skills and tactics to apprehend and stop these dangerous offenders.",
    link: "https://steamdb.info/app/2547150/",
  },
  {
    src: "/img/categories/car/6.jpg",
    name: "TOKYO RACER",
    category: ["Sport", "Multiplayer", "Online"],
    star: "4",
    path: "/img/details/car/6.jpg",
    desc: " is a racing game set in a blocked-off future Tokyo, where players aim to be the fastest by driving their best cars on the highways that weave through the city.",
    link: "https://steamdb.info/sub/944899/",
  },
  {
    src: "/img/categories/car/7.jpg",
    name: "TRAFFIC RACER HIGWAY",
    category: ["Sport", "Multiplayer", "Online"],
    star: "1",
    path: "/img/details/car/7.jpg",
    desc: "Multiplayer highway car racing, with amazing missions, daily event , and Friends Challenge",
    link: "https://steamdb.info/app/2432980/",
  },
  {
    src: "/img/categories/car/8.jpg",
    name: "SUPER KART",
    category: ["Sport", "Multiplayer", "Online"],
    star: "2.6",
    path: "/img/details/car/8.jpg",
    desc: "Super Kart Mini Car Race is an exciting and colorful racing game in the style of Classic Kart. Offering players a thrilling experience on 13 different race tracks with themes ranging from the kitchen to the bedroom, bathroom, and the beach.",
    link: "https://steamdb.info/app/2791790/",
  },
  {
    src: "/img/categories/car/9.jpg",
    name: "LORD OF THE RACE",
    category: ["Sport", "Multiplayer", "Online"],
    star: "3.7",
    path: "/img/details/car/9.jpg",
    desc: "Welcome to a Horror Open World, Story-Driven, Racing RPG Game. You have shipwrecked on Carbon Crest Island. The Deal is Sealed. Either, Race and Win through the deadly race trials set up by the deranged Count Levoy OR Lose & Suffer an eternity under his mercy.",
    link: "https://steamdb.info/app/2504040/",
  },
];

export const sport = [
  {
    src: "/img/categories/sport/1.jpg",
    name: "FIFA 22",
    category: ["Sport", "Multiplayer", "Online"],
    star: "5",
    path: "/img/details/sport/1.jpg",
    desc: "Powered by Football™, EA SPORTS™ FIFA 22 brings the game even closer to the real thing with fundamental gameplay advances and a new season of innovation across every mode.",
    link: "https://steamdb.info/app/1506830/",
  },

  {
    src: "/img/categories/sport/2.jpg",
    name: "PRO EVOULUTION SOCKER 25",
    category: ["Sport", "Multiplayer", "Online"],
    star: "4.5",
    path: "/img/details/sport/2.jpg",
    desc: "EA SPORTS FC™ 25 gives you more ways to win for the club. Team up with friends in your favourite modes with the new 5v5 Rush, and manage your club to victory as FC IQ delivers more tactical control than ever before.",
    link: "https://steamdb.info/app/2669320/",
  },
  {
    src: "/img/categories/sport/3.jpg",
    name: "PRO EVOULUTION SOCKER 19",
    category: ["Sport", "Multiplayer", "Online"],
    star: "5",
    path: "/img/details/sport/3.jpg",
    desc: "Feel The Power Of Football with PES 2019 offering new licenses, photo-realism and new myClub!",
    link: "https://steamdb.info/app/770240/",
  },
  {
    src: "/img/categories/sport/4.jpg",
    name: "PRO EVOULUTION SOCKER 16",
    category: ["Sport", "Multiplayer", "Online"],
    star: "3",
    path: "/img/categories/sport/4.jpg",
    desc: "Feel The Power Of Football with PES 2016 offering new licenses, photo-realism and new myClub!",
    link: "https://steamdb.info/app/376890/",
  },
  {
    src: "/img/categories/sport/5.jpg",
    name: "PRO EVOULUTION SOCKER 13",
    category: ["Sport", "Multiplayer", "Online"],
    star: "5",
    path: "/img/categories/sport/5.jpg",
    desc: "Feel The Power Of Football with PES 2013 offering new licenses, photo-realism and new myClub!",
    link: "https://steamdb.info/app/221430/",
  },
  {
    src: "/img/categories/sport/6.jpg",
    name: "DREAM TEAM",
    category: ["Sport", "Multiplayer", "Online"],
    star: "4",
    path: "/img/details/sport/6.jpg",
    desc: "Dream Team Basketball combines traditional CCG gameplay with innovative mechanics inspired from the game of basketball. Explore over 300 player cards and 400 traits and skills to create your team and engage in a competitive environment.",
    link: "https://steamdb.info/app/2152630/",
  },
  {
    src: "/img/categories/sport/7.jpg",
    name: "WACkY WORLD OF SPORT",
    category: ["Sport", "Multiplayer", "Online"],
    star: "1",
    path: "/img/details/sport/7.jpg",
    desc: "Get ready for Basketball, Soccer, Golf and Tennis combined into one Looney Tunes sport game! Gain power-ups to incite chaos against your friends and family as you control your favorite Looney Tunes character in 4-player, local co-op mayhem, but watch out for falling anvils!",
    link: "https://steamdb.info/app/2330430/",
  },
  {
    src: "/img/categories/sport/8.jpg",
    name: "ALEX THE BALL",
    category: ["Sport", "Multiplayer", "Online"],
    star: "2.6",
    path: "/img/details/sport/8.jpg",
    desc: "Alex has turned into a ball after an experiment went wrong. As he navigates Things get even more complicated when he finds himself in a parallel universe. A physics-based 3D platformer that can be completed in one go, if you don't fall, die, or quit.",
    link: "https://steamdb.info/app/3026830/",
  },
  {
    src: "/img/categories/sport/9.jpg",
    name: "BEAMNG.DRIVE",
    category: ["Sport", "Multiplayer", "Online"],
    star: "3.7",
    path: "/img/details/sport/9.jpg",
    desc: "A dynamic soft-body physics vehicle simulator capable of doing just about anything.",
    link: "https://steamdb.info/app/284160/",
  },
];

export const war = [
  {
    src: "/img/categories/war/1.jpg",
    name: "SNIPER",
    category: ["war", "Multiplayer", "Online"],
    star: "5",
    path: "/img/details/war/1.jpg",
    desc: "Virtual Sniper invites you to step into the shoes of a professional sniper and embark on an adrenaline-fueled adventure. Engage in missions set across three unique and immersive environments: a bustling city, a remote oil field, and a seemingly peaceful neighborhood.",
    link: "https://steamdb.info/app/3396420/",
  },

  {
    src: "/img/categories/war/2.jpg",
    name: "FARCRY 1",
    category: ["war", "Multiplayer", "Online"],
    star: "4.5",
    path: "/img/details/war/2.jpg",
    desc: "A tropical paradise seethes with hidden evil in Far Cry®, a cunningly detailed action shooter that pushes the boundaries of combat to shocking new levels. Freelance mariner Jack Carver is cursing the day he ever came to this island.",
    link: "https://steamdb.info/app/13520/",
  },
  {
    src: "/img/categories/war/3.jpg",
    name: "FARCRY 2",
    category: ["war", "Multiplayer", "Online"],
    star: "5",
    path: "/img/details/war/3.jpg",
    desc: "You are a gun for hire, trapped in a war-torn African state, stricken with malaria and forced to make deals with corrupt warlords on both sides of the conflict in order to make this country your home. You must identify and exploit your enemies' weaknesses, neutralizing their superior numbers and firepower with surprise, subversion,...",
    link: "https://steamdb.info/app/19900/",
  },
  {
    src: "/img/categories/war/4.jpg",
    name: "CALL OF DUTY 4",
    category: ["war", "Multiplayer", "Online"],
    star: "3",
    path: "/img/details/war/4.jpg",
    desc: "The new action-thriller from the award-winning team at Infinity Ward, the creators of the Call of Duty® series, delivers the most intense and cinematic action experience ever. Call of Duty 4: Modern Warfare arms gamers with an arsenal of advanced and powerful modern day firepower and transports them to the most treacherous hotspots...",
    link: "https://steamdb.info/app/7940/",
  },

  {
    src: "/img/categories/war/5.jpg",
    name: "ALIEN SHOOTER",
    category: ["war", "Multiplayer", "Online"],
    star: "2",
    path: "/img/details/war/5.jpg",
    desc: "The endless darkness and the somber, long passages of a military complex have become the abode of evil, thousands of blood-thirsty creatures fill its offices, storehouses and mysterious laboratories. About 1,000 monsters on each map, showing up to 100 monsters simultaneously on one playing screen.",
    link: "https://steamdb.info/app/33100/",
  },
  {
    src: "/img/categories/war/6.jpg",
    name: "GRAND THEFT AUTO TROLAGY",
    category: ["war", "Multiplayer", "Online"],
    star: "4",
    desc: "Experience entertainment blockbusters Grand Theft Auto V and Grand Theft Auto Online — now upgraded for a new generation with stunning visuals, faster loading, 3D audio, and more, plus exclusive content for GTA Online players.",
    path: "/img/details/war/6.jpg",
    link: "https://steamdb.info/app/3240220/",
  },
  {
    src: "/img/categories/war/7.jpg",
    name: "AVATAR 2",
    category: ["war", "Multiplayer", "Online"],
    star: "1",
    path: "/img/details/war/7.jpg",
    desc: "Avatar: Frontiers of Pandora™ is a first-person, action-adventure game set in the Western Frontier. Reconnect with your lost heritage and discover what it truly means to be Na'vi as you join other clans to protect Pandora.",
    link: "https://steamdb.info/app/2840770/",
  },
  {
    src: "/img/categories/war/8.jpg",
    name: "ANTHEM 5",
    category: ["war", "Multiplayer", "Online"],
    star: "2.6",
    path: "/img/details/war/8.jpg",
    desc: "The ultimate Devil Hunter is back in style, in the game action fans have been waiting for.",
    link: "https://steamdb.info/app/601150/",
  },
  {
    src: "/img/categories/war/9.jpg",
    name: "FLASH 2",
    category: ["war", "Multiplayer", "Online"],
    star: "3.7",
    path: "/img/details/war/9.jpg",
    desc: "Buy this armor to use it on the game while you are playing or seeing video scenes.",
    link: "https://steamdb.info/app/3366530/",
  },
];
